// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOlGrcvACZjVfOIdPJ2dGbo0fhJFRisLI',
    appId: '1:865736325048:web:63c2322c503ca3d053814d',
    messagingSenderId: '865736325048',
    projectId: 'movie-collection-73b7d',
    authDomain: 'movie-collection-73b7d.firebaseapp.com',
    storageBucket: 'movie-collection-73b7d.firebasestorage.app',
    measurementId: 'G-L9XBH00JFW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8WNzoCPkXTaFrPSED5Uuni-fxLNvluj0',
    appId: '1:865736325048:android:4b5b60700aa4092b53814d',
    messagingSenderId: '865736325048',
    projectId: 'movie-collection-73b7d',
    storageBucket: 'movie-collection-73b7d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3z4hEsuIJl2UeYsdWCSUWJXlL9XHqytM',
    appId: '1:865736325048:ios:028967cc00e071b753814d',
    messagingSenderId: '865736325048',
    projectId: 'movie-collection-73b7d',
    storageBucket: 'movie-collection-73b7d.firebasestorage.app',
    iosBundleId: 'com.example.flutterMovie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3z4hEsuIJl2UeYsdWCSUWJXlL9XHqytM',
    appId: '1:865736325048:ios:028967cc00e071b753814d',
    messagingSenderId: '865736325048',
    projectId: 'movie-collection-73b7d',
    storageBucket: 'movie-collection-73b7d.firebasestorage.app',
    iosBundleId: 'com.example.flutterMovie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOlGrcvACZjVfOIdPJ2dGbo0fhJFRisLI',
    appId: '1:865736325048:web:738590d28583db2c53814d',
    messagingSenderId: '865736325048',
    projectId: 'movie-collection-73b7d',
    authDomain: 'movie-collection-73b7d.firebaseapp.com',
    storageBucket: 'movie-collection-73b7d.firebasestorage.app',
    measurementId: 'G-5N1KEM82HF',
  );
}
